name: gamedev_helpers
version: 0.0.1-dev
description: Useful stuff for my gamedevelopment needs
author: Dennis Kaselow <Dennis.Kaselow+gamedev_helpers@gmail.com>
dependencies:
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio
  vector_math: any
  dartemis: any
  event_bus: any
