name: gamedev_helpers
description: Useful stuff for my gamedevelopment needs
author: Dennis Kaselow <Dennis.Kaselow+gamedev_helpers@gmail.com>
dev_dependencies:
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
