name: gamedev_helpers
version: 0.0.1-dev
description: Useful stuff for my gamedevelopment needs
author: Dennis Kaselow <Dennis.Kaselow+gamedev_helpers@gmail.com>
dependencies:
  vector_math: ^2.0.6
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: feature/ddc
  event_bus: 0.4.1
  tweenengine:
    git: git://github.com/KayZGames/tween-engine-dart.git
  git: ^0.5.1
  path: ^1.5.1
executables:
  setup_game:
  publish_game:
dev_dependencies:
  build_runner: ^0.8.0
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git