name: gamedev_helpers
version: 0.0.1-dev
description: Useful stuff for my gamedevelopment needs
author: Dennis Kaselow <Dennis.Kaselow+gamedev_helpers@gmail.com>
dependencies:
  vector_math: any
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: develop
  dartemis_transformer:
    path: ../dartemis_transformer
  event_bus: any
  tweenengine: any
  git: 0.4.4
  path: any
  which: any
transformers:
- dartemis_transformer
executables:
  setup_game:
  publish_game: