name: gamedev_helpers
version: 0.0.1-dev
description: Useful stuff for my gamedevelopment needs
author: Dennis Kaselow <Dennis.Kaselow+gamedev_helpers@gmail.com>
publish_to: none
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  vector_math: ^2.0.6
  dartemis: ^0.8.0
  event_bus: ^1.0.1
  tweenengine:
    git: git://github.com/KayZGames/tween-engine-dart.git
  git: ^0.5.1
  path: ^1.5.1
  aspen: ^0.3.0
  aspen_assets: ^0.3.0
executables:
  setup_game:
  publish_game:
dev_dependencies:
  build_runner: any
  dartemis_builder: ^0.1.0
  aspen_builder: ^0.3.0